---
title: "Yixuan He lab 11"
output: html_document
---
# LAB11

## Data Transforms

1. Read the Dataset "class11\_LAB\_dataFrame\_20190930T2158.csv" into a dataframe.
2. The target variable is **y**

#### Exploratory Data Analysis
1. Plot y vs.
   1. x
   2. a
   3. b
   4. c

Summarize the relationships between $y$ and the set of explanatory variables (x,a,b,c).


#### Regression
1. Please fit a simple linear regression model between **y** and **a**
2. Make a scatter plot of **y** and **a**
3. Overlay the regression line
4. Comment on the predicted model versus ground truth

#### Transforms
1. Transform **a** 4 different ways
2. Fit a linear regression
3. Overlay the regression line
4. Comment on the predicted model versus ground truth

#### Residuals
1. Plot a histogram of the above 4 model residuals

#### QQ
1. Plot a qqplot of the above 4 model residuals

How do the residuals and qq plot compare between your 4 different transforms?

#### MLR
1. Please fit a multiple linear regression model between **y** and (**x**, **a**, **b**, **c**)
2. Plot a histogram of the above 4 model residuals
3. Plot a qqplot of the above 4 model residuals

1. Does your MLR satisfy the LINE assumptions?
2. If not, what transforms do you recommend be applied to each explanatory variable and why?
3. Transform the variable you feel most violates the LINE assumptions.
4. Does transforming this variable help? why or why not?

